# ================================
# DATABASE (SQL Server)
# ================================
spring:
  datasource:
    url: jdbc:sqlserver://transitview-sql.database.windows.net:1433;databaseName=transitviewdb;encrypt=true;trustServerCertificate=false;
    username: Gruppe18Admin
    password: TransitVIEW2025MMR
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # ================================
  # JPA / Hibernate
  # ================================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
